/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*-
   !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
   This file is built by regen_perly.pl from perly.y.
   Any changes made here will be lost!
 */

#define PERL_BISON_VERSION  20007

#ifdef PERL_CORE
/* A Bison parser, made by GNU Bison 2.7.12-4996.  */

/* Bison interface for Yacc-like parsers in C
   
      Copyright (C) 1984, 1989-1990, 2000-2013 Free Software Foundation, Inc.
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
   
   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Enabling traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     GRAMPROG = 258,
     GRAMEXPR = 259,
     GRAMBLOCK = 260,
     GRAMBARESTMT = 261,
     GRAMFULLSTMT = 262,
     GRAMSTMTSEQ = 263,
     BAREWORD = 264,
     METHOD = 265,
     FUNCMETH = 266,
     THING = 267,
     PMFUNC = 268,
     PRIVATEREF = 269,
     QWLIST = 270,
     FUNC0OP = 271,
     FUNC0SUB = 272,
     UNIOPSUB = 273,
     LSTOPSUB = 274,
     PLUGEXPR = 275,
     PLUGSTMT = 276,
     CLASSDECL = 277,
     MACRODEF = 278,
     LABEL = 279,
     MACRO = 280,
     FORMAT = 281,
     SUB = 282,
     METHDECL = 283,
     MULTIDECL = 284,
     ANONSUB = 285,
     PACKAGE = 286,
     USE = 287,
     WHILE = 288,
     UNTIL = 289,
     IF = 290,
     UNLESS = 291,
     ELSE = 292,
     ELSIF = 293,
     CONTINUE = 294,
     FOR = 295,
     GIVEN = 296,
     WHEN = 297,
     DEFAULT = 298,
     LOOPEX = 299,
     DOTDOT = 300,
     YADAYADA = 301,
     FUNC0 = 302,
     FUNC1 = 303,
     FUNC = 304,
     UNIOP = 305,
     LSTOP = 306,
     RELOP = 307,
     EQOP = 308,
     MULOP = 309,
     UNIMULOP = 310,
     ADDOP = 311,
     DOLSHARP = 312,
     DO = 313,
     HASHBRACK = 314,
     NOAMP = 315,
     LOCAL = 316,
     MY = 317,
     HAS = 318,
     REQUIRE = 319,
     COLONATTR = 320,
     FORMLBRACK = 321,
     FORMRBRACK = 322,
     PREC_LOW = 323,
     DOROP = 324,
     OROP = 325,
     ANDOP = 326,
     NOTOP = 327,
     ASSIGNOP = 328,
     DORDOR = 329,
     OROR = 330,
     ANDAND = 331,
     BITOROP = 332,
     BITANDOP = 333,
     SHIFTOP = 334,
     MATCHOP = 335,
     REFGEN = 336,
     UMINUS = 337,
     POWCOP = 338,
     POWOP = 339,
     POSTJOIN = 340,
     POSTDEC = 341,
     POSTINC = 342,
     PREDEC = 343,
     PREINC = 344,
     ARROW = 345
   };
#endif

/* Tokens.  */
#define GRAMPROG 258
#define GRAMEXPR 259
#define GRAMBLOCK 260
#define GRAMBARESTMT 261
#define GRAMFULLSTMT 262
#define GRAMSTMTSEQ 263
#define BAREWORD 264
#define METHOD 265
#define FUNCMETH 266
#define THING 267
#define PMFUNC 268
#define PRIVATEREF 269
#define QWLIST 270
#define FUNC0OP 271
#define FUNC0SUB 272
#define UNIOPSUB 273
#define LSTOPSUB 274
#define PLUGEXPR 275
#define PLUGSTMT 276
#define CLASSDECL 277
#define MACRODEF 278
#define LABEL 279
#define MACRO 280
#define FORMAT 281
#define SUB 282
#define METHDECL 283
#define MULTIDECL 284
#define ANONSUB 285
#define PACKAGE 286
#define USE 287
#define WHILE 288
#define UNTIL 289
#define IF 290
#define UNLESS 291
#define ELSE 292
#define ELSIF 293
#define CONTINUE 294
#define FOR 295
#define GIVEN 296
#define WHEN 297
#define DEFAULT 298
#define LOOPEX 299
#define DOTDOT 300
#define YADAYADA 301
#define FUNC0 302
#define FUNC1 303
#define FUNC 304
#define UNIOP 305
#define LSTOP 306
#define RELOP 307
#define EQOP 308
#define MULOP 309
#define UNIMULOP 310
#define ADDOP 311
#define DOLSHARP 312
#define DO 313
#define HASHBRACK 314
#define NOAMP 315
#define LOCAL 316
#define MY 317
#define HAS 318
#define REQUIRE 319
#define COLONATTR 320
#define FORMLBRACK 321
#define FORMRBRACK 322
#define PREC_LOW 323
#define DOROP 324
#define OROP 325
#define ANDOP 326
#define NOTOP 327
#define ASSIGNOP 328
#define DORDOR 329
#define OROR 330
#define ANDAND 331
#define BITOROP 332
#define BITANDOP 333
#define SHIFTOP 334
#define MATCHOP 335
#define REFGEN 336
#define UMINUS 337
#define POWCOP 338
#define POWOP 339
#define POSTJOIN 340
#define POSTDEC 341
#define POSTINC 342
#define PREDEC 343
#define PREINC 344
#define ARROW 345


#ifdef PERL_IN_TOKE_C
static bool
S_is_opval_token(int type) {
    switch (type) {
    case BAREWORD:
    case CLASSDECL:
    case FUNC0OP:
    case FUNC0SUB:
    case FUNCMETH:
    case LSTOPSUB:
    case MACRODEF:
    case METHOD:
    case PLUGEXPR:
    case PLUGSTMT:
    case PMFUNC:
    case PRIVATEREF:
    case QWLIST:
    case THING:
    case UNIOPSUB:
	return 1;
    }
    return 0;
}
#endif /* PERL_IN_TOKE_C */
#endif /* PERL_CORE */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{
/* Line 2053 of yacc.c  */

    I32	ival; /* __DEFAULT__ (marker for regen_perly.pl;
				must always be 1st union member) */
    char *pval;
    OP *opval;
    GV *gvval;


/* Line 2053 of yacc.c  */
} YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
#endif


#ifdef YYPARSE_PARAM
#if defined __STDC__ || defined __cplusplus
int yyparse (void *YYPARSE_PARAM);
#else
int yyparse ();
#endif
#else /* ! YYPARSE_PARAM */
#if defined __STDC__ || defined __cplusplus
int yyparse (void);
#else
int yyparse ();
#endif
#endif /* ! YYPARSE_PARAM */


#if YYDEBUG
#define YYPRINT
#endif

/* Generated from:
 * 1f589f6be197bd1b08c6a4148de328e722ccaded7a456c479bd522918c4a923f perly.y
 * 25c852d9fc4ee1fa7741d85b998cb1c114ca562f098ad0e98d8b0a15aadf00f9 regen_perly.pl
 * ex: set ro: */
